### ISSUE TITLE
Question: Did you tried to use PyPy ?

### ISSUE THREAD

**Issue by Yardanico** [gulcu/CalculatePI#1]
I tried to run it on PyPy(pure python version), and on CPython( with NumPy)
The results are:
"time python calcnumpy.py"(I deleted code associated with pure python version):
`()
('Actual PI = ', 3.141592653589793)
()
('PI Calculated using NumPy = ', 3.0)
('Difference = ', -0.14159265358979312)
(32.298547, 'seconds process time with NumPy')
python calcnumpy.py  32,16s user 0,29s system 100% cpu 32,214 total
`

"time pypy calculatepi.py"(I deleted numpy code, although numpy can work with pypy this days)
`()
('Actual PI = ', 3.141592653589793)
()
('PI Calculated using Standard Python = ', 3)
('Difference = ', -0.14159265358979312)
(44.937142918999996, 'seconds process time without NumPy')
()
pypy calculatepi.py  45,02s user 0,04s system 99% cpu 45,076 total`
I think that's a HUGE boost to standart Python :)

**Comment by gulcu** [comment]
I have a deadline for another project due in 3 weeks and do not have the time to look into PyPy now because I have never used it before. However, while the focus is on speed, a difference of 0.14 is too much since even kids use 3.14 or 22/7 as an estimate of PI. Thank you for reminding me of PyPy, I plan to return and compare NumPy with PyPy and even C by the end of September!

**Comment by TiberiumPY** [comment]
But NumPy shows the same difference.

**Comment by gulcu** [comment]
Not on my computer. It's probably because I am using Python 3, are you using Python 2? Division should be like "//" instead of "/", or one of the numerator or the denominator needs to be cast into double because the result seems to be "truncated".

**Comment by TiberiumPY** [comment]
i'm using Python 2, sure.
I will try PyPy3 right now(Mozilla recently donated $200 000 to PyPy in order to add Py3.5 support, so they are working hard):
The result of running PyPy3:
`Actual PI =  3.141592653589793

PI Calculated using Standard Python =  3.141589092
Difference =  -3.56158979331056e-06
44.658305 seconds process time without NumPy

pypy3 calculatepi.py  44,70s user 0,00s system 99% cpu 44,716 total`

**Comment by TiberiumPY** [comment]
And I will run NumPy on Python 3 right now

**Comment by TiberiumPY** [comment]
Result:
`Actual PI =  3.141592653589793

PI Calculated using NumPy =  3.141607384
Difference =  1.47304102067e-05
32.800169000000004 seconds process time with NumPy
python3 calcnumpy.py  32,87s user 0,09s system 100% cpu 32,906 total`

**Comment by TiberiumPY** [comment]
The PyPy3 Pi result is closer than NumPy xD

**Comment by TiberiumPY** [comment]
OK, thank you for answering - if you need to download PyPy2 or PyPy3 - check this links:
http://buildbot.pypy.org/nightly/py3.5/  - PyPy3 builds(nightly)
http://buildbot.pypy.org/nightly/trunk/ - PyPy2 builds

**Comment by gulcu** [comment]
I would love to see Python running at near-C speeds without external libraries. I shall definitely look into PyPy sometime in October, after my project deadline passes. Thank you again for reminding me.
